// VARIABLES CON LET


let producto = "audifonos gamers"; // Iniciar letible y asignar el valor

let disponible; // Iniciamos la letiblae pero sin valor


disponible = true;

let producto1 = "computadora",
    disponible1 = true,
    categoria = "computadora";


// let 1disponible; NO ESTA PERMITIDO
// let - disponible; NO ESTA PERMITIDO

// Estilos para las letiables
let nombre_producto = "Monitor HD"; // Underscore
let nombreProducto = "Monitor HD"; // Camel case
let NombreProduto = "Monitor HD"; // Pascal case


console.log(producto);